print("Hello World!")
print(5+3)
print("Python","is","fun!")
print("She said,\"Hello!\"")
print("First Line\nSecond line")
print("item 1\titem 2\titem 3")
print("The result is", 42)
print(12345)
print(3.14159)
print("Dollar sign:$")
print("apple", "banana", "cherry", sep=",")
print ("Hello,", end=" ")
print("World!")
print("Python!"* 3)
print()
print("Hello" + "World!")
print(True)
print(False)
print(1.2e3) # Prints 1200.0
print("""This is a multiline print statement""")
print("This is a backsheet: \\")
